import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import test from 'node:test';

function read(path) {
  return readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');
}

test('settings expose microphone input and live calibration controls', () => {
  const html = read('index.html');
  const app = read('src/app.js');
  const microphoneSession = read('src/platform/microphone-session.js');
  const micRecordingDiagnostic = read('src/platform/mic-recording-diagnostic.js');
  const staffRenderer = read('src/ui/staff-renderer.js');

  assert.match(html, /data-input-mode="microphone"/);
  assert.match(html, />Sing\/Play<\/button>/);
  assert.match(html, /id="start-microphone"/);
  assert.match(html, /id="stop-microphone"/);
  assert.match(html, /id="microphone-status"/);
  assert.match(html, /id="calibration-reading"/);
  assert.match(html, /Actual calibration/);
  assert.match(html, /Grant mic/);
  assert.match(html, /Sing any comfortable note/);
  assert.match(html, /data-app-version="clefhanger-slice51-mic-octave-match-toggle/);
  assert.match(app, /const appVersion = 'clefhanger-slice51-mic-octave-match-toggle-2026-09-02'/);
  assert.match(app, /\.\/core\/mic-diagnostics\.js\?v=clefhanger-slice51-mic-octave-match-toggle-2026-09-02/);
  assert.match(html, /id="record-microphone-diagnostic"/);
  assert.match(html, /id="microphone-recording-diagnostic"/);
  assert.match(html, /Record 1s test/);
  assert.match(html, /Mic Lab/);
  assert.match(html, /id="mic-lab-label"/);
  assert.match(html, /id="export-mic-report"/);
  assert.match(html, /Export mic report/);
  assert.match(html, /id="mic-report-preview"/);
  assert.match(html, /id="match-any-octave"/);
  assert.match(html, /Match any octave/);
  assert.match(html, /low or high C counts as C/);

  assert.match(microphoneSession, /Microphone permission denied/);
  assert.match(microphoneSession, /tap the lock/);
  assert.match(microphoneSession, /Android Settings/);
  assert.match(microphoneSession, /navigatorObject\.permissions\.query/);
  assert.match(microphoneSession, /queryMicrophonePermissionState/);
  assert.match(app, /formatMicrophoneError/);
  assert.match(app, /Requesting mic/);
  assert.match(app, /calibrationReadingText/);
  assert.match(microphoneSession, /withMicrophoneRequestTimeout/);
  assert.match(microphoneSession, /Microphone request timed out/);
  assert.match(app, /buildMicrophoneListeningMessage/);
  assert.match(app, /getCenteredRms/);
  assert.match(app, /silentFrameCount/);
  assert.match(app, /microphoneSession/);
  assert.match(microphoneSession, /createMediaStreamSource\(stream\)/);
  assert.match(microphoneSession, /keepAliveGain/);
  assert.match(microphoneSession, /createGain\(\)/);
  assert.match(microphoneSession, /connect\(audioContext\.destination\)/);
  assert.match(app, /getCurrentMicrophoneTrackState/);
  assert.match(app, /recordMicrophoneDiagnostic/);
  assert.match(app, /buildMicDiagnosticReport/);
  assert.match(app, /buildMicDiagnosticTextFile/);
  assert.match(app, /downloadMicReport/);
  assert.match(app, /requestAnimationFrame\(\(timestamp\) => processMicrophoneFrame\(null, timestamp\)\)/);
  assert.doesNotMatch(app, /requestAnimationFrame\(processMicrophoneFrame\)/);
  assert.match(micRecordingDiagnostic, /detectPitchFromRecordedAudio/);
  assert.match(app, /buildBeginnerMicMessage/);
  assert.match(micRecordingDiagnostic, /MediaRecorderClass/);
  assert.match(micRecordingDiagnostic, /recorder\.start\(timesliceMs\)/);
  assert.match(micRecordingDiagnostic, /recorder\.requestData\?\.\(\)/);
  assert.match(app, /MediaRecorder returned 0 bytes/);
  assert.match(app, /live mic level/);
  assert.match(micRecordingDiagnostic, /decodeAudioData/);
  assert.match(app, /getMicrophoneRecordingDiagnostic/);
  assert.match(microphoneSession, /navigatorObject\.mediaDevices\.getUserMedia/);
  assert.match(microphoneSession, /getBuiltInVocalMicrophoneConstraints\(\)/);
  assert.doesNotMatch(app, /getUserMedia\(\{ audio: true \}\)/);
  assert.match(app, /formatDiagnosticLevelPercent\(result\.decodedRms\)/);
  assert.match(app, /selectInputMode: \(inputMode\)/);
  assert.match(app, /microphone/);
  assert.match(app, /processMicrophoneFrame/);
  assert.match(app, /clefhangerInjectPitch/);
  assert.match(app, /evaluateVocalMatchFrame/);
  assert.match(app, /matchAnyOctave/);
  assert.match(app, /vocalCandidate/);
  assert.match(app, /pending-stable/);
  assert.match(staffRenderer, /createGhostNoteFromPitch/);
  assert.match(staffRenderer, /class=\"ghost-note\"/);
  assert.match(staffRenderer, /Ghost note you played/);
  assert.match(app, /\['running', 'practice'\]\.includes\(state\.phase\)/);
});
